// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: booking/v1/booking.proto

package bookingv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateBookingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBookingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBookingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBookingRequestMultiError, or nil if none found.
func (m *CreateBookingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBookingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for HairdresserId

	// no validation rules for ServiceId

	// no validation rules for SalonId

	if all {
		switch v := interface{}(m.GetStartsAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateBookingRequestValidationError{
					field:  "StartsAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateBookingRequestValidationError{
					field:  "StartsAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartsAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateBookingRequestValidationError{
				field:  "StartsAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndsAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateBookingRequestValidationError{
					field:  "EndsAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateBookingRequestValidationError{
					field:  "EndsAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndsAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateBookingRequestValidationError{
				field:  "EndsAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Description

	// no validation rules for Status

	if len(errors) > 0 {
		return CreateBookingRequestMultiError(errors)
	}

	return nil
}

// CreateBookingRequestMultiError is an error wrapping multiple validation
// errors returned by CreateBookingRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateBookingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBookingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBookingRequestMultiError) AllErrors() []error { return m }

// CreateBookingRequestValidationError is the validation error returned by
// CreateBookingRequest.Validate if the designated constraints aren't met.
type CreateBookingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBookingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBookingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBookingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBookingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBookingRequestValidationError) ErrorName() string {
	return "CreateBookingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBookingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBookingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBookingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBookingRequestValidationError{}

// Validate checks the field values on CreateBookingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateBookingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateBookingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateBookingResponseMultiError, or nil if none found.
func (m *CreateBookingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateBookingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetBooking()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateBookingResponseValidationError{
					field:  "Booking",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateBookingResponseValidationError{
					field:  "Booking",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetBooking()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateBookingResponseValidationError{
				field:  "Booking",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateBookingResponseMultiError(errors)
	}

	return nil
}

// CreateBookingResponseMultiError is an error wrapping multiple validation
// errors returned by CreateBookingResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateBookingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateBookingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateBookingResponseMultiError) AllErrors() []error { return m }

// CreateBookingResponseValidationError is the validation error returned by
// CreateBookingResponse.Validate if the designated constraints aren't met.
type CreateBookingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateBookingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateBookingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateBookingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateBookingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateBookingResponseValidationError) ErrorName() string {
	return "CreateBookingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateBookingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateBookingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateBookingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateBookingResponseValidationError{}

// Validate checks the field values on GetBookingRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetBookingRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBookingRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBookingRequestMultiError, or nil if none found.
func (m *GetBookingRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBookingRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	switch v := m.Method.(type) {
	case *GetBookingRequest_Username:
		if v == nil {
			err := GetBookingRequestValidationError{
				field:  "Method",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Username
	case *GetBookingRequest_Id:
		if v == nil {
			err := GetBookingRequestValidationError{
				field:  "Method",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for Id
	case *GetBookingRequest_HairdresserId:
		if v == nil {
			err := GetBookingRequestValidationError{
				field:  "Method",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for HairdresserId
	case *GetBookingRequest_ServiceId:
		if v == nil {
			err := GetBookingRequestValidationError{
				field:  "Method",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for ServiceId
	case *GetBookingRequest_SalonId:
		if v == nil {
			err := GetBookingRequestValidationError{
				field:  "Method",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}
		// no validation rules for SalonId
	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return GetBookingRequestMultiError(errors)
	}

	return nil
}

// GetBookingRequestMultiError is an error wrapping multiple validation errors
// returned by GetBookingRequest.ValidateAll() if the designated constraints
// aren't met.
type GetBookingRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBookingRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBookingRequestMultiError) AllErrors() []error { return m }

// GetBookingRequestValidationError is the validation error returned by
// GetBookingRequest.Validate if the designated constraints aren't met.
type GetBookingRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBookingRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBookingRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBookingRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBookingRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBookingRequestValidationError) ErrorName() string {
	return "GetBookingRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetBookingRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBookingRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBookingRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBookingRequestValidationError{}

// Validate checks the field values on GetBookingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetBookingResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetBookingResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetBookingResponseMultiError, or nil if none found.
func (m *GetBookingResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetBookingResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetBookings() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetBookingResponseValidationError{
						field:  fmt.Sprintf("Bookings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetBookingResponseValidationError{
						field:  fmt.Sprintf("Bookings[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetBookingResponseValidationError{
					field:  fmt.Sprintf("Bookings[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetBookingResponseMultiError(errors)
	}

	return nil
}

// GetBookingResponseMultiError is an error wrapping multiple validation errors
// returned by GetBookingResponse.ValidateAll() if the designated constraints
// aren't met.
type GetBookingResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetBookingResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetBookingResponseMultiError) AllErrors() []error { return m }

// GetBookingResponseValidationError is the validation error returned by
// GetBookingResponse.Validate if the designated constraints aren't met.
type GetBookingResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetBookingResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetBookingResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetBookingResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetBookingResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetBookingResponseValidationError) ErrorName() string {
	return "GetBookingResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetBookingResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetBookingResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetBookingResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetBookingResponseValidationError{}

// Validate checks the field values on Bookings with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Bookings) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Bookings with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BookingsMultiError, or nil
// if none found.
func (m *Bookings) ValidateAll() error {
	return m.validate(true)
}

func (m *Bookings) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Username

	// no validation rules for HairdresserId

	// no validation rules for ServiceId

	// no validation rules for SalonId

	if all {
		switch v := interface{}(m.GetStartsAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingsValidationError{
					field:  "StartsAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingsValidationError{
					field:  "StartsAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStartsAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingsValidationError{
				field:  "StartsAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEndsAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingsValidationError{
					field:  "EndsAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingsValidationError{
					field:  "EndsAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEndsAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingsValidationError{
				field:  "EndsAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for Description

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingsValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingsValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingsValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BookingsValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BookingsValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BookingsValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return BookingsMultiError(errors)
	}

	return nil
}

// BookingsMultiError is an error wrapping multiple validation errors returned
// by Bookings.ValidateAll() if the designated constraints aren't met.
type BookingsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BookingsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BookingsMultiError) AllErrors() []error { return m }

// BookingsValidationError is the validation error returned by
// Bookings.Validate if the designated constraints aren't met.
type BookingsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BookingsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BookingsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BookingsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BookingsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BookingsValidationError) ErrorName() string { return "BookingsValidationError" }

// Error satisfies the builtin error interface
func (e BookingsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBookings.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BookingsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BookingsValidationError{}
