// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: booking/v1/booking.proto

package bookingv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusBooking int32

const (
	StatusBooking_BOOKING_STATUS_UNSPECIFIED StatusBooking = 0
	StatusBooking_BOOKING_STATUS_PENDING     StatusBooking = 1
	StatusBooking_BOOKING_STATUS_CONFIRMED   StatusBooking = 2
	StatusBooking_BOOKING_STATUS_COMPLETED   StatusBooking = 3
	StatusBooking_BOOKING_STATUS_CANCELLED   StatusBooking = 4
	StatusBooking_BOOKING_STATUS_NO_SHOW     StatusBooking = 5
)

// Enum value maps for StatusBooking.
var (
	StatusBooking_name = map[int32]string{
		0: "BOOKING_STATUS_UNSPECIFIED",
		1: "BOOKING_STATUS_PENDING",
		2: "BOOKING_STATUS_CONFIRMED",
		3: "BOOKING_STATUS_COMPLETED",
		4: "BOOKING_STATUS_CANCELLED",
		5: "BOOKING_STATUS_NO_SHOW",
	}
	StatusBooking_value = map[string]int32{
		"BOOKING_STATUS_UNSPECIFIED": 0,
		"BOOKING_STATUS_PENDING":     1,
		"BOOKING_STATUS_CONFIRMED":   2,
		"BOOKING_STATUS_COMPLETED":   3,
		"BOOKING_STATUS_CANCELLED":   4,
		"BOOKING_STATUS_NO_SHOW":     5,
	}
)

func (x StatusBooking) Enum() *StatusBooking {
	p := new(StatusBooking)
	*p = x
	return p
}

func (x StatusBooking) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusBooking) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_v1_booking_proto_enumTypes[0].Descriptor()
}

func (StatusBooking) Type() protoreflect.EnumType {
	return &file_booking_v1_booking_proto_enumTypes[0]
}

func (x StatusBooking) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusBooking.Descriptor instead.
func (StatusBooking) EnumDescriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	HairdresserId string                 `protobuf:"bytes,2,opt,name=hairdresser_id,json=hairdresserId,proto3" json:"hairdresser_id,omitempty"`
	ServiceId     int32                  `protobuf:"varint,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	SalonId       int32                  `protobuf:"varint,4,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Status        StatusBooking          `protobuf:"varint,8,opt,name=status,proto3,enum=booking.v1.StatusBooking" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBookingRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateBookingRequest) GetHairdresserId() string {
	if x != nil {
		return x.HairdresserId
	}
	return ""
}

func (x *CreateBookingRequest) GetServiceId() int32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *CreateBookingRequest) GetSalonId() int32 {
	if x != nil {
		return x.SalonId
	}
	return 0
}

func (x *CreateBookingRequest) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *CreateBookingRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *CreateBookingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBookingRequest) GetStatus() StatusBooking {
	if x != nil {
		return x.Status
	}
	return StatusBooking_BOOKING_STATUS_UNSPECIFIED
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Bookings              `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookingResponse) GetBooking() *Bookings {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetBookingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Method:
	//
	//	*GetBookingRequest_Username
	//	*GetBookingRequest_Id
	//	*GetBookingRequest_HairdresserId
	//	*GetBookingRequest_ServiceId
	//	*GetBookingRequest_SalonId
	Method        isGetBookingRequest_Method `protobuf_oneof:"method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookingRequest) GetMethod() isGetBookingRequest_Method {
	if x != nil {
		return x.Method
	}
	return nil
}

func (x *GetBookingRequest) GetUsername() string {
	if x != nil {
		if x, ok := x.Method.(*GetBookingRequest_Username); ok {
			return x.Username
		}
	}
	return ""
}

func (x *GetBookingRequest) GetId() int32 {
	if x != nil {
		if x, ok := x.Method.(*GetBookingRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetBookingRequest) GetHairdresserId() string {
	if x != nil {
		if x, ok := x.Method.(*GetBookingRequest_HairdresserId); ok {
			return x.HairdresserId
		}
	}
	return ""
}

func (x *GetBookingRequest) GetServiceId() int32 {
	if x != nil {
		if x, ok := x.Method.(*GetBookingRequest_ServiceId); ok {
			return x.ServiceId
		}
	}
	return 0
}

func (x *GetBookingRequest) GetSalonId() int32 {
	if x != nil {
		if x, ok := x.Method.(*GetBookingRequest_SalonId); ok {
			return x.SalonId
		}
	}
	return 0
}

type isGetBookingRequest_Method interface {
	isGetBookingRequest_Method()
}

type GetBookingRequest_Username struct {
	Username string `protobuf:"bytes,1,opt,name=username,proto3,oneof"`
}

type GetBookingRequest_Id struct {
	Id int32 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

type GetBookingRequest_HairdresserId struct {
	HairdresserId string `protobuf:"bytes,3,opt,name=hairdresser_id,json=hairdresserId,proto3,oneof"`
}

type GetBookingRequest_ServiceId struct {
	ServiceId int32 `protobuf:"varint,4,opt,name=service_id,json=serviceId,proto3,oneof"`
}

type GetBookingRequest_SalonId struct {
	SalonId int32 `protobuf:"varint,5,opt,name=salon_id,json=salonId,proto3,oneof"`
}

func (*GetBookingRequest_Username) isGetBookingRequest_Method() {}

func (*GetBookingRequest_Id) isGetBookingRequest_Method() {}

func (*GetBookingRequest_HairdresserId) isGetBookingRequest_Method() {}

func (*GetBookingRequest_ServiceId) isGetBookingRequest_Method() {}

func (*GetBookingRequest_SalonId) isGetBookingRequest_Method() {}

type GetBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Bookings            `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingResponse) Reset() {
	*x = GetBookingResponse{}
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingResponse) ProtoMessage() {}

func (x *GetBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingResponse.ProtoReflect.Descriptor instead.
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{3}
}

func (x *GetBookingResponse) GetBookings() []*Bookings {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type Bookings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	HairdresserId string                 `protobuf:"bytes,2,opt,name=hairdresser_id,json=hairdresserId,proto3" json:"hairdresser_id,omitempty"`
	ServiceId     int32                  `protobuf:"varint,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	SalonId       int32                  `protobuf:"varint,4,opt,name=salon_id,json=salonId,proto3" json:"salon_id,omitempty"`
	StartsAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=starts_at,json=startsAt,proto3" json:"starts_at,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Status        StatusBooking          `protobuf:"varint,8,opt,name=status,proto3,enum=booking.v1.StatusBooking" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bookings) Reset() {
	*x = Bookings{}
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bookings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bookings) ProtoMessage() {}

func (x *Bookings) ProtoReflect() protoreflect.Message {
	mi := &file_booking_v1_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bookings.ProtoReflect.Descriptor instead.
func (*Bookings) Descriptor() ([]byte, []int) {
	return file_booking_v1_booking_proto_rawDescGZIP(), []int{4}
}

func (x *Bookings) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Bookings) GetHairdresserId() string {
	if x != nil {
		return x.HairdresserId
	}
	return ""
}

func (x *Bookings) GetServiceId() int32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *Bookings) GetSalonId() int32 {
	if x != nil {
		return x.SalonId
	}
	return 0
}

func (x *Bookings) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Bookings) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *Bookings) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bookings) GetStatus() StatusBooking {
	if x != nil {
		return x.Status
	}
	return StatusBooking_BOOKING_STATUS_UNSPECIFIED
}

func (x *Bookings) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Bookings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_booking_v1_booking_proto protoreflect.FileDescriptor

const file_booking_v1_booking_proto_rawDesc = "" +
	"\n" +
	"\x18booking/v1/booking.proto\x12\n" +
	"booking.v1\x1a'googleapis/google/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x02\n" +
	"\x14CreateBookingRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12%\n" +
	"\x0ehairdresser_id\x18\x02 \x01(\tR\rhairdresserId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\x05R\tserviceId\x12\x19\n" +
	"\bsalon_id\x18\x04 \x01(\x05R\asalonId\x127\n" +
	"\tstarts_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x121\n" +
	"\x06status\x18\b \x01(\x0e2\x19.booking.v1.StatusBookingR\x06status\"G\n" +
	"\x15CreateBookingResponse\x12.\n" +
	"\abooking\x18\x01 \x01(\v2\x14.booking.v1.BookingsR\abooking\"\xb4\x01\n" +
	"\x11GetBookingRequest\x12\x1c\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x12\x10\n" +
	"\x02id\x18\x02 \x01(\x05H\x00R\x02id\x12'\n" +
	"\x0ehairdresser_id\x18\x03 \x01(\tH\x00R\rhairdresserId\x12\x1f\n" +
	"\n" +
	"service_id\x18\x04 \x01(\x05H\x00R\tserviceId\x12\x1b\n" +
	"\bsalon_id\x18\x05 \x01(\x05H\x00R\asalonIdB\b\n" +
	"\x06method\"F\n" +
	"\x12GetBookingResponse\x120\n" +
	"\bbookings\x18\x01 \x03(\v2\x14.booking.v1.BookingsR\bbookings\"\xc0\x03\n" +
	"\bBookings\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12%\n" +
	"\x0ehairdresser_id\x18\x02 \x01(\tR\rhairdresserId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\x05R\tserviceId\x12\x19\n" +
	"\bsalon_id\x18\x04 \x01(\x05R\asalonId\x127\n" +
	"\tstarts_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bstartsAt\x123\n" +
	"\aends_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x121\n" +
	"\x06status\x18\b \x01(\x0e2\x19.booking.v1.StatusBookingR\x06status\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*\xc1\x01\n" +
	"\rStatusBooking\x12\x1e\n" +
	"\x1aBOOKING_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16BOOKING_STATUS_PENDING\x10\x01\x12\x1c\n" +
	"\x18BOOKING_STATUS_CONFIRMED\x10\x02\x12\x1c\n" +
	"\x18BOOKING_STATUS_COMPLETED\x10\x03\x12\x1c\n" +
	"\x18BOOKING_STATUS_CANCELLED\x10\x04\x12\x1a\n" +
	"\x16BOOKING_STATUS_NO_SHOW\x10\x052\xef\x01\n" +
	"\x0eBookingService\x12w\n" +
	"\rCreateBooking\x12 .booking.v1.CreateBookingRequest\x1a!.booking.v1.CreateBookingResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/booking/create\x12d\n" +
	"\n" +
	"GetBooking\x12\x1d.booking.v1.GetBookingRequest\x1a\x1e.booking.v1.GetBookingResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/bookingBAZ?github.com/nhassl3/hairdress_arz_52/pkg/pb/booking/v1;bookingv1b\x06proto3"

var (
	file_booking_v1_booking_proto_rawDescOnce sync.Once
	file_booking_v1_booking_proto_rawDescData []byte
)

func file_booking_v1_booking_proto_rawDescGZIP() []byte {
	file_booking_v1_booking_proto_rawDescOnce.Do(func() {
		file_booking_v1_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)))
	})
	return file_booking_v1_booking_proto_rawDescData
}

var file_booking_v1_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_booking_v1_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_booking_v1_booking_proto_goTypes = []any{
	(StatusBooking)(0),            // 0: booking.v1.StatusBooking
	(*CreateBookingRequest)(nil),  // 1: booking.v1.CreateBookingRequest
	(*CreateBookingResponse)(nil), // 2: booking.v1.CreateBookingResponse
	(*GetBookingRequest)(nil),     // 3: booking.v1.GetBookingRequest
	(*GetBookingResponse)(nil),    // 4: booking.v1.GetBookingResponse
	(*Bookings)(nil),              // 5: booking.v1.Bookings
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_booking_v1_booking_proto_depIdxs = []int32{
	6,  // 0: booking.v1.CreateBookingRequest.starts_at:type_name -> google.protobuf.Timestamp
	6,  // 1: booking.v1.CreateBookingRequest.ends_at:type_name -> google.protobuf.Timestamp
	0,  // 2: booking.v1.CreateBookingRequest.status:type_name -> booking.v1.StatusBooking
	5,  // 3: booking.v1.CreateBookingResponse.booking:type_name -> booking.v1.Bookings
	5,  // 4: booking.v1.GetBookingResponse.bookings:type_name -> booking.v1.Bookings
	6,  // 5: booking.v1.Bookings.starts_at:type_name -> google.protobuf.Timestamp
	6,  // 6: booking.v1.Bookings.ends_at:type_name -> google.protobuf.Timestamp
	0,  // 7: booking.v1.Bookings.status:type_name -> booking.v1.StatusBooking
	6,  // 8: booking.v1.Bookings.created_at:type_name -> google.protobuf.Timestamp
	6,  // 9: booking.v1.Bookings.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 10: booking.v1.BookingService.CreateBooking:input_type -> booking.v1.CreateBookingRequest
	3,  // 11: booking.v1.BookingService.GetBooking:input_type -> booking.v1.GetBookingRequest
	2,  // 12: booking.v1.BookingService.CreateBooking:output_type -> booking.v1.CreateBookingResponse
	4,  // 13: booking.v1.BookingService.GetBooking:output_type -> booking.v1.GetBookingResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_booking_v1_booking_proto_init() }
func file_booking_v1_booking_proto_init() {
	if File_booking_v1_booking_proto != nil {
		return
	}
	file_booking_v1_booking_proto_msgTypes[2].OneofWrappers = []any{
		(*GetBookingRequest_Username)(nil),
		(*GetBookingRequest_Id)(nil),
		(*GetBookingRequest_HairdresserId)(nil),
		(*GetBookingRequest_ServiceId)(nil),
		(*GetBookingRequest_SalonId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_v1_booking_proto_rawDesc), len(file_booking_v1_booking_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_v1_booking_proto_goTypes,
		DependencyIndexes: file_booking_v1_booking_proto_depIdxs,
		EnumInfos:         file_booking_v1_booking_proto_enumTypes,
		MessageInfos:      file_booking_v1_booking_proto_msgTypes,
	}.Build()
	File_booking_v1_booking_proto = out.File
	file_booking_v1_booking_proto_goTypes = nil
	file_booking_v1_booking_proto_depIdxs = nil
}
